# Generated by Django 5.0.2 on 2024-02-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Client',
        ),
    ]
